### ISSUE TITLE
What still needs doing?

### ISSUE THREAD

**Issue by GrahamSH-LLK** [Hans5958/ScratchAddons-Website-Hugo#2]
I'm willing to help with anything that needs doing, so it would be great if you could give me some things to work on! 
cc @Hans5958

**Comment by Hans5958** [comment]
I actually have no roadmap to follow for this, but the general thing is to move the pages, make pages translatable, and do the docs and blog (maybe). There's nothing you could help on the code side, but if you want, how about prepare the docs for moving, and maybe granting access on TX since I forgot to ask, and it's for testing how the localization.
